// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-ratex.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RatexSpec.h"

@interface Ratex : NSObject <NativeRatexSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Ratex : NSObject <RCTBridgeModule>
#endif

@end